# Generated by Django 5.1.2 on 2024-10-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(default=1)),
                ('level_text', models.CharField(default='Beginner', max_length=255)),
                ('count_of_money', models.IntegerField(default=0)),
                ('count_of_exp', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='ImageData',
        ),
    ]
